apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: httpd-example-prod
  namespace: cpredhat
spec:
  template:
    spec:
      volumes:
      - name: drtest
        persistentVolumeClaim:
          claimName: drtest2
