kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drtest2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
